### PR TITLE
[WIP] Behaviors: Saturating, Wrapping

### PR DESCRIPTION
**Pull request by regexident**
Attempts to resolve issue https://github.com/andylokandy/arraydeque/issues/6 according to:

> - Add a type parameter on `ArrayDeuqe`, determining whether to enable wrapping behavior, which would look like `ArrayDeque<[usize; 64], Wrapping>`, and disable as default.

Curious as to what you think about it, @andylokandy. 🙂
Consider this a work-in-progress.

Sorry for the big commit. The type change forced me to touch basically everything before it compiled again.

### CODE REVIEW

**Comment by andylokandy** [comment]
Seems we was working on same thing at the same time. Since we both have our own implementation, how about to compare and to pick the best part of each?

**Comment by regexident** [comment]
Sure!

**Comment by andylokandy** [comment]
AFAICS, we've basically same implementation strategy, with different name.

 Other differents:
- `prepend` is a good idea!
- you have great doc!!!
- whether or not to add a new trait. I chose not to because I think it adds complexity for the beginner and those who don't need wrapping behavior. 
- whether or not to expose unchecked push methods. I chose not to for the same reason.

**Comment by regexident** [comment]
> AFAICS, we've basically same implementation strategy, with different names.

Yeah, looks like it.

I chose `Wrapping`/`Saturating` as both terms are known from Rust's integer arithmetic:

- [wrapping_add](http://doc.rust-lang.org/1.21.0/std/primitive.i32.html#method.wrapping_add)
- [saturating_add](http://doc.rust-lang.org/1.21.0/std/primitive.i128.html#method.saturating_add)

> Other differences:

> - prepend is a good idea!

I figured a deque should not be biased towards appending any more than necessary.

As such I also added `extend_front()` and `extend_back()`.

> - you made great doc!!!

Thanks!

> - whether or not to add a new trait. I chose not to because I think it adds complexity for the beginner and those who don't need wrapping behavior.

The benefit of the trait would be that you can find all compatible types from the docs, easily, by looking up the trait from the compiler error, when providing a nonsense type.

> - whether or not to expose unchecked push methods. I chose not to for the same reason.

👍🏻

> - convert methods between two types

Good one! I've added `fn wrapping(self)` and `fn saturating(self)`. `From<ArrayDeque<T, U>>` unfortunately is blocked by stdlib's `impl<T> From<T> for T {}`.

**Comment by andylokandy** [comment]
So far so good! Would you mind to rebase your work onto 'develop' branch? https://github.com/andylokandy/arraydeque/commit/c0244a263c7f5b04608655045cef18b8d2a3f252, ignoring the last commit.

**Comment by regexident** [comment]
Done.

**Comment by regexident** [comment]
🎉 🙇🏻‍♂️

**Comment by regexident** [comment]
FYI: https://github.com/japaric/heapless/blob/master/src/ring_buffer/mod.rs

**Comment by andylokandy** [comment]
@regexident Cool, multi-thread support. People that want concurrent use ['deque'](https://crates.io/search?q=deque), while others that want interruption handling in embedded environment use `heapless`. For other basic usages, `arrayvec` and `arraydeque` should be enough. 
Thank for bring this up.

**Pull request merged**
