### PR TITLE
Rotating, overwriting ring buffer

### PR DESCRIPTION
**Pull request by SuperFluffy**
I needed a ring buffer which, when full, would overwrite the other end and forget the first (or last) object pushed into it. While `ArrayDeque::push_back` (and `::push_front`) will hand `element` back to the caller when it's full, `RotatingDeque::push_back` will replace `RotatingDeque::first` with `element` and return the now overwitten object.

There is a lot of code duplication still going on, but I wanted to see what you think of this PR. I think one could provide a `BaseDeque` struct and implement `ArrayDeque` and `RotatingDeque` in terms of a `Deque` trait, where one defines the `push_back`, `push_front`, `pop_back`, and `pop_front` methods.

What do you think of this?

### CODE REVIEW

**Comment by SuperFluffy** [comment]
Yeah, those massive changes are certainly too much. :-) I think most can be refactored into a common basic struct (similar to what ndarray is doing with `ArrayBase`).

The problem with introducing, e.g., `push_back_overlay` and `push_front_overlay` on `ArrayDeque` is that all its other methods, in particular all trait impls, would still work with the standard `push_back` and `push_front`. That's why I was thinking about creating a new struct instead.

**Comment by goandylok** [comment]
@SupperFluffy Your reasons are very convincing, I have not taken into account this point. 
I am not very concerned about the internal implementation, as long as we keep 
the interface clean. In addition, I think **trait** is not suitable. Because trait is used to define some interface rather than to reduce code duplication. `Arraybase` or even simply copy-and-paste are very elegant solutions, because this as a small basic crate, has no foreseeable  feature changes in the future. 
But I recently did not have time to make this big refactor, if you can go ahead
, I am very grateful.

**Comment by SuperFluffy** [comment]
Yeah, I just started considering how to do go about the refactor, and quickly realized that traits are completely non-sensical. :-(

I am thinking about using some kind of (zero-cost) newtype definition like `struct ArrayDeque(BaseDeque)` and `RotatingDeque(BaseDeque), implement `push_back` and `push_front` for the newtypes, and forward all trait impls to `BaseDeque`.

**Comment by goandylok** [comment]
That's a good idea, but it's not idiomatic, and I'm afraid that will bring learning costs to the user.

**Comment by goandylok** [comment]
@SuperFluffy You know, not everyone need the feature, so not everybody have to suffer from this complexity.

**Comment by andylokandy** [comment]
Closing for implementation. Thank you again @SuperFluffy .

**Pull request closed without merging**
